### ISSUE TITLE
[3] Plan specifications and tasks for model selection feature

### ISSUE THREAD

**Issue by hirotoshi-uchino-hacarus** [hacarus/progress-management#168]
***In GitLab by @jason on Jul 6, 2022, 14:02 GMT+9:***

**Assignees:** jason

*Migrated from GitLab: https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/214*

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Jul 8, 2022, 13:24 GMT+9:***

Candidate tasks to register in kanban:

- [x] [3] Prepare scenario-unified sample model files based on updated SAA → #244 
    - Current version uses multiple indexed ctx & param pb files per scenario, but future plan is to organize all into a single ctx and param pb/json files per scenario.
    - Main purpose is to serve as sample model files for testing updated app.
    - Update config repo as necessary.
- [x] [3] Execute model loading upon scenario switching → #245 
    - Current app implementation executes model loading within ImageProcessor.Inspect method. In relation to the plan of model files being organized into single ctx and param pb files per scenario, model loading has to be taken out from Inspect method and moved to the part where scenario gets switched.
- [x] [3] Switch model based on target inspection katashiki number → #246 
    - Upon inspection start, 型式 number will have to be indicated based on pre-detected markings on the target for proper model selection.
    - Apply appropriate model & sensitivity settings based on 型式 number selected.
- [x] [3] Migrate sensitivity file from csv to json format → #247 
    - Based on initial discussions with Kimura-san, `.json` is the preferred format.
- [x] [5] Add special processing setting in scenario handling → #248 
    - Add additional masks required for special processing under `mask/`.
        - Define name and indexing rule (`smask.<s>.png`?).
        - For usual predict, use `mask.<p>.png`?
    - Add special sensitivity files for special processing under `sensitivity/`
        - Define name and indexing rule (`ssen.<型式番号n>.<s>.json`)
        - For usual predict, use `sen.<型式番号n>.json`?
    - Add `specialProcess.csv` which will list all desired sequences of special processes.
        - When mask is required, include reference to additional mask prior to the special process itself.
        - Contents should also indicate whether or not to bypass predict.
        - Indicate special process.
        - Indicate special sensitivity.
    - Edit `sequence.csv` to indicate any special processing requirement.
        - Refer to an item in `specialProcess.csv`.
    - Update config repo as necessary.
    - Update parsing scenario files.
- [x] [5] Apply special processing along or instead of predict as additional option within inspect method → #249 
    - Familiarize with updated SddCs sample program to understand usage of updated API for special processing.
    - Apply required special processing depending on parsed info from `sequence.csv` & `specialProcess.csv`.
    - Handle accumulation of detected rectangles from predict + additional special processing.
