### ISSUE TITLE
[3] Plan specification and tasks for flow modification necessary to capture mold number

### ISSUE THREAD

**Issue by hirotoshi-uchino-hacarus** [hacarus/progress-management#170]
***In GitLab by @jason on Jul 6, 2022, 14:16 GMT+9:***

**Assignees:** jason

*Migrated from GitLab: https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/216*

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Jul 12, 2022, 14:51 GMT+9:***

Candidate tasks to register in kanban:

- [x] [5] Auto-identification of katashiki number → #250 
    - Use some image processing for auto-identification.
    - Method would be best made available separately from `ImageProcessor` class.
- [x] [1] Prepare preInspect csv file containing sequence for model number capture → #251 
    - `preInspect.csv` will be in the same format as `sequence.csv`.
    - update `arm.csv`, `table.csv`, `camera.csv` and `light.csv` to include settings required for model number capture.
    - refer to updated csv files when preparing `preInspect.csv`.
- [x] [5] Add preInspect sequence handling → #252 
    - Modify `ScenarioProvider.LoadSequence()` to be reusable for both `sequence.csv` and `preInspect.csv` parsing.
    - Add `PreInspect` list under `MovementProvider`.
    - Add movement sequence source switch as an argument to `MovementProvider.Move()` to properly branch out between `PreInspect` and `Sequence` lists.
    - Add `PreInspectRequest` flag in `ImageProvider` to indicate whether a frame is for katashiki number identification purpose.
    - Add a branch under `ImageProviderNewFrame()` to process `PreInspectRequest` frames.
        - Add call to katashiki number auto-identification.
    - Feed output of katshiki number auto-identification in `ImageProcessor` constructor to load appropriate models for the current katashiki.
