### ISSUE TITLE
[5] Implement SSD to HDD auto data transfer for inspection results

### ISSUE THREAD

**Issue by hirotoshi-uchino-hacarus** [hacarus/progress-management#784]
***In GitLab by @jason on Feb 28, 2023, 16:43 GMT+9:***

# Specs

Please see #949.

# TODO

- [x] Prepare `storage.yaml`
- [x] Add yaml file parser for new settings
    - [x] `ResultStoragePath`
    - [x] `DataMoveDay`
    - [x] `DataMoveStart`
    - [x] `DataMoveDuration`
- [x] Add data move logic
    - [x] Copy via [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#remarks)
    - [x] Add [MD5 checksum comparison](https://stackoverflow.com/questions/10520048/calculate-md5-checksum-for-a-file)
    - [x] Add copy retry for checksum comparison failures (only one time)
    - [x] Delete original files
    - [x] Add scheduling logic based on `storage.yaml` settings
- [x] Revise result list to refer to both `ResultStoragePath` and app install path
    - [x] Data viewing logic
    - [x] Data deletion logic
- [x] Move and revise disk status settings from `config.csv` to `storage.yaml`
    - [x] `PrimaryDiskWarning`
    - [x] `PrimaryDiskDelete`
    - [x] `SecondaryDiskWarning`
    - [x] `SecondaryDiskDelete`
- [x] Revise disk status GUI
    - [x] Separate primary (SSD) and secondary (HDD)
    - [x] Add `Backing-up` / `転送中` status
- [x] Add timeout logic based on `DataMoveDuration` setting
- [x] Add other GUI related logic
    - [x] Add manual backup start option in context menu (app header right click menu)
    - [x] Add backup cancel option in context menu
    - [x] Disable other controls during backup
- [x] Add old data overwrite logic for data moving based on destination disk status
    - [x] Add size estimator for all files to be copied
    - [x] Delete oldest files based on `SecondaryDiskDelete` setting
- [x] Add `storage.yaml` settings validity checker
- [x] Resolve CI/CD failure
- [x] Add test code
- [x] Prepare MR

**Assignees:** jason

*Migrated from GitLab: https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/950*

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 1, 2023, 09:30 GMT+9:***

marked this issue as related to #951

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 6, 2023, 14:41 GMT+9:***

marked the checklist item **Prepare `storage.yaml`** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 6, 2023, 15:46 GMT+9:***

marked the checklist item **`ResultStoragePath`** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 6, 2023, 15:47 GMT+9:***

marked the checklist item **`DataMoveDuration`** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 6, 2023, 15:47 GMT+9:***

marked the checklist item **Add yaml file parser for new settings** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 6, 2023, 18:05 GMT+9:***

marked the checklist item **Copy via [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#remarks)** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 7, 2023, 15:45 GMT+9:***

marked the checklist item **Add [MD5 checksum comparison](https://stackoverflow.com/questions/10520048/calculate-md5-checksum-for-a-file)** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 8, 2023, 07:45 GMT+9:***

marked the checklist item **Add data move logic** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 9, 2023, 11:29 GMT+9:***

marked the checklist item **Data deletion logic** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 9, 2023, 11:29 GMT+9:***

marked the checklist item **Revise result list to refer to both `ResultStoragePath` and app install path** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 9, 2023, 13:42 GMT+9:***

marked the checklist item **`PrimaryDiskWarning`** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 9, 2023, 13:42 GMT+9:***

marked the checklist item **`PrimaryDiskDelete`** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 9, 2023, 13:48 GMT+9:***

marked the checklist item **`SecondaryDiskWarning`** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 9, 2023, 13:48 GMT+9:***

marked the checklist item **`SecondaryDiskDelete`** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 13, 2023, 16:59 GMT+9:***

marked the checklist item **Add timeout logic based on `DataMoveDuration` setting** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 14, 2023, 13:19 GMT+9:***

marked the checklist item **Delete oldest files based on `SecondaryDiskDelete` setting** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 14, 2023, 13:19 GMT+9:***

marked the checklist item **Add old data overwrite logic for data moving based on destination disk status** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 15, 2023, 10:01 GMT+9:***

marked the checklist item **Resolve CI/CD failure** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 15, 2023, 17:32 GMT+9:***

marked the checklist item **Add test code** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 15, 2023, 17:32 GMT+9:***

marked the checklist item **Prepare MR** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 15, 2023, 17:32 GMT+9:***

marked the checklist item **Prepare MR** as incomplete

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 15, 2023, 19:44 GMT+9:***

mentioned in merge request hacarus-check-robo-frontend!170

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on Mar 15, 2023, 20:13 GMT+9:***

marked the checklist item **Prepare MR** as completed
