### ISSUE TITLE
[3] Implement SSD to HDD auto data transfer for train data

### ISSUE THREAD

**Issue by hirotoshi-uchino-hacarus** [hacarus/progress-management#796]
***In GitLab by @jason on Mar 6, 2023, 14:03 GMT+9:***

# Specs

Please see #973.

# TODO
 
- [x] Add train data move logic
    - [x] Copy via [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#remarks)
    - [x] Add [MD5 checksum comparison](https://stackoverflow.com/questions/10520048/calculate-md5-checksum-for-a-file)
    - [x] Delete original files
    - [x] Add copy retry for checksum comparison failures (only one time)
    - [x] Schedule before result data move
- [x] Revise train data list to refer to both `storagePath` and app install path
    - [x] Data viewing logic
    - [x] Data deletion logic
- [x] Revise `Extract` / `結果から抽出` destination to always be `storagePath`
- [x] Add old data overwrite logic for data moving based on destination disk status
- [x] Prepare MR

**Assignees:** jason

*Migrated from GitLab: https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/973*
