### ISSUE TITLE
Asahikosei:Testing before 6/2 release

### ISSUE THREAD

**Issue by hirotoshi-uchino-hacarus** [hacarus/progress-management#929]
***In GitLab by @fuka.i on May 30, 2023, 17:40 GMT+9:***

Robo 3号機を使います。
# Todo
- https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/1151
  - [x] https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/hacarus-check-robo-frontend/-/merge_requests/206
- https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/1153
  - [x] https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/hacarus-check-robo-frontend/-/merge_requests/207

- [x] リグレッションテスト：https://docs.google.com/spreadsheets/d/135F5wXvYaZN17jk0PENyYFRbeMPUtFuajjWXMrji_Qo/edit#gid=0

**Assignees:** fuka.i

*Migrated from GitLab: https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/1174*

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @fuka.i on May 31, 2023, 17:19 GMT+9:***

# 起票issue
https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/1178

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @fuka.i on May 31, 2023, 19:37 GMT+9:***

marked the checklist item **https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/hacarus-check-robo-frontend/-/merge_requests/206** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @fuka.i on May 31, 2023, 19:37 GMT+9:***

marked the checklist item **https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/hacarus-check-robo-frontend/-/merge_requests/207** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @fuka.i on May 31, 2023, 19:37 GMT+9:***

marked the checklist item **https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/hacarus-check-robo-frontend/-/merge_requests/206** as incomplete

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @fuka.i on Jun 1, 2023, 14:31 GMT+9:***

marked the checklist item **https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/hacarus-check-robo-frontend/-/merge_requests/206** as completed

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @fuka.i on Jun 1, 2023, 14:40 GMT+9:***

marked the checklist item **リグレッションテスト：https://docs.google.com/spreadsheets/d/135F5wXvYaZN17jk0PENyYFRbeMPUtFuajjWXMrji_Qo/edit#gid=0** as completed
