### ISSUE TITLE
[3] Recognize Pattern of arm, table...csv as word, not index

### ISSUE THREAD

**Issue by hirotoshi-uchino-hacarus** [hacarus/progress-management#930]
***In GitLab by @mitsutaka on May 31, 2023, 10:53 GMT+9:***

5/31 木村さんの指摘から。  
arm.csv, table.csv 等の番号付けに使っている `Pattern` にて、任意の文字列を付けられるようにしたい。  
各座標が何を示しているかを示せるようにしたいため。

**Assignees:** mitsutaka

*Migrated from GitLab: https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/1175*

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @mitsutaka on May 31, 2023, 10:58 GMT+9:***

# TODO

* [x] `SenarioProvider` で, arm, table...csvの Patternにある文字から辞書を作成する
* [x] `SenarioProvider` で sequence.csv の文字列と、前述の辞書の番号を関連付ける
* [x] 最終的に, `MovementProvider`には、 Patternの文字列は渡さず、辞書の値を渡すようにする

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @mitsutaka on May 31, 2023, 14:38 GMT+9:***

marked this issue as related to hacarus-check-robo-frontend#209
